
# Acknowledgements

The authors gratefully acknowledge the many different people who have willingly contributed their knowledge and their time to the development of GWSDAT^[Copyright Shell Global Solutions International, B.V. 2012. All rights reserved.].
 
The authors wish to express their gratitude to Ludger Evers and Daniel Molinari from the Department of Statistics, University of Glasgow, for their invaluable contributions to the statistical aspects of GWSDAT. Thanks also to Ewan Crawford for his assistance in the development of the original GWSDAT user interface. 

We acknowledge and thank the R project for Statistical Computing and all its contributors without which this project would not have been possible. 

A big thank you to Shell's worldwide environmental consultants for assistance in evaluating and testing GWSDAT.  Thanks also to the Shell Year in Industry students Tess Brina, Rosemary Archard, Emma Toms, Stephanie Marrs and Rachel Stroud who spent a great deal of time using GWSDAT and making suggestions for improvements. 


Thanks to Andrew Kirkman and team from BP Remediation Solutions for contributing new functionality and enhancements in version 3.3. Thanks to Fraser Spalding who as a summer student at the University of Glasgow, almost singlehandedly, delivered the GWSDAT Tutorials YouTube Channel. Credit and acknowledgement to Jan Limbeck from Shell for providing the portable Windows R version optimized for linear algebra. 

We thank both current and former colleagues Matthew Lahvis, George Devaull, Matthijs Bonte, Hayley Thomas, Karina Cady, Jonathan Smith from the Shell SGW Projects & Technology and FDG teams and Philip Jonathan, former Shell Chief Statistician, for their support, vision and advocacy of GWSDAT.  

The original idea of GWSDAT was inspired by Marco Giannitrapani.




    