# Acknowledgements

The authors gratefully acknowledge the many different people who have willingly contributed their knowledge and their time to the development of GWSDAT.
 
The authors wish to express their gratitude to Ludger Evers, Adrian Bowman, Marnie Low and Daniel Molinari from the Department of Statistics, University of Glasgow, for their invaluable contributions to the statistical aspects of GWSDAT. Thanks also to Ewan Crawford from the University of Glasgow for his assistance in the development of the original GWSDAT user interface. 

We acknowledge and thank the R project for Statistical Computing and all its contributors without which this project would not have been possible. 

A big thank you to Shell's worldwide environmental consultants for assistance in evaluating and testing the earlier versions of GWSDAT.  Thanks also to the Shell Year in Industry students Tess Brina, Rosemary Archard, Emma Toms, Stephanie Marrs and Rachel Stroud who spent a great deal of time using GWSDAT and making suggestions for improvements. 

We thank our colleagues Matthew Lahvis, George Devaull, Dan Walsh and Curt Stanley from Shell Projects & Technology; HSE Technology: Soil & Groundwater and Philip Jonathan, Shell Chief Statistician, for their support, vision and advocacy of GWSDAT.  

The original idea of GWSDAT was inspired by Marco Giannitrapani.
